spring:
  application:
    name: razorpay
  datasource:
    url: jdbc:postgresql://localhost:5433/razorpayDB
    username: postgres
    password: Programmer@0520
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

vault:
  master-key: jkfbhguefbjfbfugewkfbsjfbsjdfgewufwebkwejb3e

payment:
  simulator:
    poll-interval-ms: 5000
    chaos-mode: NORMAL
    methods:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 3
        success-rate: 95
      NET_BANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80
jwt:
  secret_key: dev_hiuhewfinciwrughncwegcrb32y428374cbwerchbwnecer